# Default configuration for Gmail Creator
# This is a minimal configuration for getting started

account:
  batch_size: 3
  delay_between_accounts: [10, 20]
  delay_between_actions: [1, 3]
  max_retries: 3
  save_to_file: true
  output_format: "json"

browser:
  browser_type: "chromium"
  headless: false
  viewport_width: 1920
  viewport_height: 1080

proxy:
  enabled: true
  auto_fetch_free: false
  proxy_file: "config/proxies.json"
  rotation_method: "random"
  # preferred_countries: ["US", "FR", "CY", "BZ", "NL", "CZ"]
  preferred_countries: ["US",]
  health_check_interval: 300
  max_failures: 3
  timeout: 10

stealth:
  randomize_fingerprints: true
  stealth_plugin_enabled: true

logging:
  level: "INFO"
  console_enabled: true
  file_enabled: true
  colored_console: true